#!/usr/bin/env python3
"""
Sturgeon analysis module for LittleJohn.

This module provides automated Sturgeon analysis following the exact architecture
specified in the Sturgeon Analysis Model. It integrates with LittleJohn's workflow
system and processes parquet files generated by the BED conversion step.

Features:
- Automated Sturgeon analysis using parquet files from BED conversion
- Integration with robin.subpages.Sturgeon_object
- Sample-specific output directories
- Comprehensive metadata extraction and logging
- Error handling and result tracking
"""

import os
import time
import logging
from dataclasses import dataclass, field
from typing import Dict, Any, Optional, List
from pathlib import Path
from littlejohn.logging_config import get_job_logger
from robin.subpages.Sturgeon_object import sturgeon_bam_background_work


@dataclass
class SturgeonMetadata:
    """Container for Sturgeon analysis metadata and results"""

    sample_id: str
    parquet_path: str
    work_dir: str
    analysis_timestamp: float
    output_dir: Optional[str] = None
    processing_steps: List[str] = field(default_factory=list)
    error_message: Optional[str] = None
    results: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self):
        if self.processing_steps is None:
            self.processing_steps = []
        if self.results is None:
            self.results = {}


class SturgeonAnalysis:
    """Sturgeon analysis worker"""

    def __init__(self, work_dir=None):
        self.work_dir = work_dir or os.getcwd()

        # Use logger for initialization
        logger = logging.getLogger("littlejohn.sturgeon")
        logger.info(f"Sturgeon Analysis initialized")
        logger.debug(f"Work directory: {self.work_dir}")

    def process_parquet_file(
        self, parquet_path: str, sample_id: str, work_dir: str
    ) -> SturgeonMetadata:
        """Process a parquet file for Sturgeon analysis"""
        logger = logging.getLogger("littlejohn.sturgeon")

        logger.info(f"Processing parquet file: {parquet_path} for Sturgeon analysis")
        start_time = time.time()

        sturgeon_result = SturgeonMetadata(
            sample_id=sample_id,
            parquet_path=parquet_path,
            work_dir=work_dir,
            analysis_timestamp=start_time,
        )

        logger.info(f"Starting Sturgeon analysis for sample: {sample_id}")
        logger.debug(f"Parquet file: {os.path.basename(parquet_path)}")
        logger.debug(f"Work directory: {work_dir}")

        try:
            # Step 1: Check if parquet file exists and is readable
            if not os.path.exists(parquet_path):
                raise FileNotFoundError(f"Parquet file not found: {parquet_path}")

            sturgeon_result.processing_steps.append("file_validation")

            # Step 2: Create sample-specific output directory
            output_dir = os.path.join(work_dir, sample_id)
            os.makedirs(output_dir, exist_ok=True)
            sturgeon_result.output_dir = output_dir
            logger.info(f"Created output directory: {output_dir}")

            sturgeon_result.processing_steps.append("directory_created")

            # Step 3: Run Sturgeon analysis
            logger.info(f"Running Sturgeon analysis...")

            # Get reference genome and probes file
            reference_genome = "hg38"
            probes_file = self._get_probes_file(reference_genome)

            # Get current timestamp in milliseconds
            current_time = time.time() * 1000

            # Run Sturgeon analysis
            self._run_sturgeon_analysis(
                parquet_path, output_dir, probes_file, current_time
            )

            sturgeon_result.processing_steps.append("sturgeon_analysis_complete")

            logger.info(f"Sturgeon analysis complete for {sample_id}")
            logger.info(f"   Output directory: {output_dir}")
            logger.info(f"   Reference genome: {reference_genome}")
            logger.info(f"   Probes file: {os.path.basename(probes_file)}")

            return sturgeon_result

        except Exception as e:
            logger.error(f"Error in Sturgeon analysis for {sample_id}: {e}")
            sturgeon_result.error_message = str(e)
            sturgeon_result.processing_steps.append("analysis_failed")
            return sturgeon_result

    def _get_probes_file(self, reference_genome: str) -> str:
        """Get the probes file path for the given reference genome"""
        import os
        import sturgeon

        probes_file = os.path.join(
            os.path.dirname(sturgeon.__file__),
            "include/static",
            f"probes_{reference_genome}.bed",
        )
        return probes_file

    def _run_sturgeon_analysis(
        self, parquet_path: str, output_dir: str, probes_file: str, current_time: float
    ) -> None:
        """Run the actual Sturgeon analysis"""
        logger = logging.getLogger("littlejohn.sturgeon")

        try:
            # Run the analysis directly using the top-level import
            # Create the output file path for sturgeon results
            # sturgeon_output_file = os.path.join(output_dir, "sturgeon.csv")
            sturgeon_bam_background_work(
                parquet_path, output_dir, str(probes_file), current_time
            )
            logger.debug(f"Sturgeon analysis completed successfully")

        except Exception as e:
            logger.error(f"Sturgeon analysis failed: {e}")
            raise


def sturgeon_handler(job, work_dir=None):
    """
    Handler function for Sturgeon analysis jobs.
    This function processes parquet files for Sturgeon analysis.

    Args:
        job: The workflow job containing file and metadata
        work_dir: Optional base directory for output (defaults to parquet file directory)
    """
    try:
        # Get job-specific logger
        logger = get_job_logger(str(job.job_id), job.job_type, job.context.filepath)
        logger.info(
            f"Starting Sturgeon analysis for: {os.path.basename(job.context.filepath)}"
        )

        # Get metadata from previous steps
        bed_conversion_result = job.context.results.get("bed_conversion", {})
        bam_metadata = job.context.metadata.get("bam_metadata", {})

        # Extract parquet path from bed conversion results
        parquet_path = bed_conversion_result.get("parquet_path")
        if not parquet_path:
            raise ValueError("No parquet path found from bed conversion step")

        # Get sample ID
        sample_id = bam_metadata.get("sample_id", "unknown")

        # Determine work directory
        if work_dir is None:
            # Default to parquet file directory
            work_dir = os.path.dirname(parquet_path)
        else:
            # Use specified work directory, create if it doesn't exist
            os.makedirs(work_dir, exist_ok=True)
            logger.debug(f"Using specified work directory: {work_dir}")

        # Create Sturgeon analysis instance
        sturgeon_analyzer = SturgeonAnalysis(work_dir=work_dir)

        # Process the parquet file
        sturgeon_result = sturgeon_analyzer.process_parquet_file(
            parquet_path, sample_id, work_dir
        )

        # Store results in job context
        job.context.add_metadata("sturgeon_analysis", sturgeon_result.results)
        job.context.add_metadata(
            "sturgeon_processing_steps", sturgeon_result.processing_steps
        )

        if sturgeon_result.error_message:
            job.context.add_error("sturgeon_analysis", sturgeon_result.error_message)
            logger.error(f"Sturgeon analysis failed: {sturgeon_result.error_message}")
        else:
            job.context.add_result(
                "sturgeon_analysis",
                {
                    "status": "success",
                    "sample_id": sturgeon_result.sample_id,
                    "analysis_time": sturgeon_result.analysis_timestamp,
                    "output_dir": sturgeon_result.output_dir,
                    "processing_steps": sturgeon_result.processing_steps,
                },
            )
            logger.info(
                f"Sturgeon analysis complete for {os.path.basename(job.context.filepath)}"
            )
            logger.info(f"Sample ID: {sturgeon_result.sample_id}")
            logger.info(f"Output directory: {sturgeon_result.output_dir}")
            logger.debug(
                f"Processing steps: {', '.join(sturgeon_result.processing_steps)}"
            )

    except Exception as e:
        job.context.add_error("sturgeon_analysis", str(e))
        logger.error(f"Error in Sturgeon analysis for {job.context.filepath}: {e}")
