from __future__ import annotations

from typing import Any, Dict, Optional
from pathlib import Path
import logging
import json
import os
from datetime import datetime
import threading
import queue

try:
    from nicegui import ui
except ImportError:  # pragma: no cover
    ui = None

logger = logging.getLogger("robin.gui.bed_coverage")


def _is_dark_mode() -> bool:
    """Quasar ``body--dark`` via app storage (see theme.frame)."""
    try:
        from nicegui import app

        return bool(app.storage.user.get("dark_mode"))
    except Exception:
        return False


def _bed_cov_echart_palette(dark: bool) -> Dict[str, str]:
    """Axis, title, legend, tooltip for BED coverage ECharts (design.md §5, §6)."""
    if dark:
        return {
            "text": "#e2e8f0",
            "muted": "#94a3b8",
            "axis_line": "#64748b",
            "split": "rgba(148, 163, 184, 0.38)",
            "tooltip_bg": "rgba(15, 23, 42, 0.96)",
            "tooltip_border": "#334155",
        }
    return {
        "text": "#0f172a",
        "muted": "#475569",
        "axis_line": "#94a3b8",
        "split": "rgba(71, 85, 105, 0.33)",
        "tooltip_bg": "rgba(255, 255, 255, 0.98)",
        "tooltip_border": "#e2e8f0",
    }


def _apply_bed_cov_echart_chrome(echart: Any, dark: bool) -> None:
    """Apply light/dark readable chrome without touching series data."""
    p = _bed_cov_echart_palette(dark)
    try:
        o = echart.options
        if not isinstance(o, dict):
            return
        o["backgroundColor"] = "transparent"
        o["textStyle"] = {"color": p["text"]}
        title = o.get("title")
        if isinstance(title, dict):
            title["textStyle"] = {"color": p["text"], "fontSize": 16}
        o["tooltip"] = {
            **(o.get("tooltip") or {}),
            "backgroundColor": p["tooltip_bg"],
            "borderColor": p["tooltip_border"],
            "textStyle": {"color": p["text"]},
        }
        leg = o.get("legend")
        if isinstance(leg, dict):
            leg["textStyle"] = {"color": p["muted"]}
        xa = o.get("xAxis")
        if isinstance(xa, dict):
            xa["axisLine"] = {"lineStyle": {"color": p["axis_line"]}}
            xa["axisLabel"] = {**(xa.get("axisLabel") or {}), "color": p["muted"]}
            xa["nameTextStyle"] = {"color": p["muted"]}
            xa["splitLine"] = {"lineStyle": {"color": p["split"]}}
        ya = o.get("yAxis")
        if isinstance(ya, dict):
            ya["axisLine"] = {"lineStyle": {"color": p["axis_line"]}}
            ya["axisLabel"] = {**(ya.get("axisLabel") or {}), "color": p["muted"]}
            ya["nameTextStyle"] = {"color": p["muted"]}
            ya["splitLine"] = {"lineStyle": {"color": p["split"]}}
    except Exception:
        pass


def _load_visualization_data(sample_dir: Path) -> Optional[Dict[str, Any]]:
    """
    Load pre-processed visualization data from JSON file.
    This data is generated by the analysis code to avoid doing heavy work in the GUI.

    Args:
        sample_dir: Sample directory path

    Returns:
        Dictionary with 'series' list for ECharts, or None if file not found or invalid
    """
    viz_file = sample_dir / "bed_coverage_viz.json"

    if not viz_file.exists():
        logger.debug(f"[BED Coverage] Visualization file not found: {viz_file}")
        return None

    try:
        with open(viz_file, "r") as f:
            data = json.load(f)
            if isinstance(data, dict) and "series" in data:
                return data
            else:
                logger.warning(f"Visualization file has invalid format: {viz_file}")
                return None
    except (json.JSONDecodeError, IOError) as e:
        logger.warning(f"Could not load visualization data: {e}")
        return None


def add_bed_coverage_section(launcher: Any, sample_dir: Path) -> None:
    """
    Add BED coverage visualization section to the GUI.
    Shows genome coverage proportions for each BED file type over time.

    Args:
        launcher: GUI launcher instance
        sample_dir: Sample directory path
    """
    if ui is None:
        logger.warning("[BED Coverage] ui is None, returning early")
        return

    logger.info(
        f"[BED Coverage] add_bed_coverage_section() called with sample_dir: {sample_dir}"
    )

    # Local state for this section
    state: Dict[str, Any] = {
        "mtime": None,
        "chart": None,
        "status_container": None,
        "bed_summary": None,
        "update_in_progress": False,
        "result_queue": queue.Queue(),
        "chart_data": None,
        "bed_cov_plot_theme_dark": None,
    }

    def _update_ui(result: Optional[Dict[str, Any]]) -> None:
        """Update UI on main thread with results from background work."""
        try:
            # None means skip update (data unchanged)
            if result is None:
                return

            # Check if we have valid data
            if result.get("chart_data") is None:
                # Show message if visualization file not found or empty
                if state["status_container"]:
                    state["status_container"].clear()
                    state["status_container"].classes("w-full mt-2", replace="hidden")
                    with state["status_container"]:
                        ui.label("No BED coverage visualization data found").classes(
                            "classification-insight-meta w-full"
                        )
                        ui.label(
                            "(Coverage data will appear after master BED files are generated)"
                        ).classes("classification-insight-foot w-full")
                if state["bed_summary"]:
                    state["bed_summary"].text = "No visualization data"
                if state["chart"]:
                    state["chart"].classes("hidden", replace="w-full h-96")
                _d = _is_dark_mode()
                if state["chart"]:
                    _apply_bed_cov_echart_chrome(state["chart"], _d)
                    try:
                        state["chart"].update()
                    except Exception:
                        pass
                    state["bed_cov_plot_theme_dark"] = _d
                return

            # Update state
            state["mtime"] = result["mtime"]
            state["chart_data"] = result["chart_data"]
            chart_data = result["chart_data"]

            n_series = len(chart_data.get("series") or [])
            if state["bed_summary"]:
                state["bed_summary"].text = (
                    f"{n_series} BED type{'s' if n_series != 1 else ''} tracked over time"
                    if n_series
                    else "No series to display"
                )

            # Update chart if it exists and we have series to plot
            if state["chart"]:
                if chart_data["series"]:
                    logger.debug(
                        f"[BED Coverage] Updating chart with {len(chart_data['series'])} series"
                    )

                    # Extract legend data from series
                    legend_data = [s["name"] for s in chart_data["series"]]

                    # Hide status container and ensure chart is visible BEFORE update
                    if state["status_container"]:
                        state["status_container"].classes("hidden")
                    # Ensure chart is visible - remove hidden class explicitly, then set classes
                    state["chart"].classes(remove="hidden")
                    state["chart"].classes("w-full h-96")

                    # Update chart options
                    # Important: Directly modify the options dict in place
                    state["chart"].options["series"] = chart_data["series"]
                    state["chart"].options["legend"]["data"] = legend_data
                    # Update yAxis to format values as percentages
                    if "yAxis" in state["chart"].options:
                        state["chart"].options["yAxis"]["axisLabel"] = {
                            "formatter": "{value}%"
                        }

                    _d = _is_dark_mode()
                    _apply_bed_cov_echart_chrome(state["chart"], _d)
                    state["bed_cov_plot_theme_dark"] = _d

                    # Force update
                    state["chart"].update()
                    logger.debug(
                        f"[BED Coverage] Chart updated with {len(chart_data['series'])} series"
                    )
                else:
                    logger.warning(
                        "[BED Coverage] No series data to plot (all data points filtered out?)"
                    )
                    if state["status_container"]:
                        state["status_container"].classes(
                            "w-full mt-2", replace="hidden"
                        )
                        state["status_container"].clear()
                        with state["status_container"]:
                            ui.label(
                                "Coverage data exists but no valid data points to plot"
                            ).classes("classification-insight-meta w-full")
                    if state["bed_summary"]:
                        state["bed_summary"].text = "No valid data points to plot"
                    state["chart"].classes("hidden", replace="w-full h-96")
            else:
                # This shouldn't happen, but handle gracefully
                logger.warning("[BED Coverage] Chart element not initialized")
        except Exception as e:
            logger.exception(f"[BED Coverage] Failed to update UI: {e}")
            if state["status_container"]:
                state["status_container"].clear()
                state["status_container"].classes("w-full mt-2", replace="hidden")
                with state["status_container"]:
                    ui.label(f"Error loading coverage data: {str(e)}").classes(
                        "text-red-600"
                    )
            if state["bed_summary"]:
                state["bed_summary"].text = "Error loading visualization"
            if state["chart"]:
                state["chart"].classes("hidden", replace="w-full h-96")

    def _update_coverage_plot() -> None:
        """Update the coverage plot. Data is pre-processed by analysis code."""

        def _do_heavy_work() -> Optional[Dict[str, Any]]:
            """Load pre-processed visualization data in background thread."""
            try:
                viz_file = sample_dir / "bed_coverage_viz.json"
                if not viz_file.exists():
                    return {"mtime": None, "chart_data": None}

                current_mtime = viz_file.stat().st_mtime

                # Skip if mtime hasn't changed and we already have data
                if current_mtime == state.get("mtime") and state.get("chart_data") is not None:
                    logger.debug("[BED Coverage] Data unchanged, skipping update")
                    return None  # Signal to skip UI update

                # Load pre-processed visualization data
                chart_data = _load_visualization_data(sample_dir)

                if chart_data and chart_data.get("series"):
                    logger.debug(
                        f"[BED Coverage] Loaded visualization data with {len(chart_data['series'])} series"
                    )
                    return {
                        "mtime": current_mtime,
                        "chart_data": chart_data,
                    }
                else:
                    # File exists but no valid data
                    return {"mtime": current_mtime, "chart_data": None}
            except Exception as e:
                logger.exception(f"[BED Coverage] Error in background work: {e}")
            return None

        # Run heavy work in background thread, then put result in queue
        def _run_update():
            try:
                result = _do_heavy_work()
                # Put result in queue for main thread to pick up
                state["result_queue"].put(result)
            except Exception as e:
                logger.exception(f"[BED Coverage] Error in background thread: {e}")
                state["result_queue"].put(None)
            finally:
                state["update_in_progress"] = False

        # Check if update is already in progress
        if state.get("update_in_progress", False):
            logger.debug("[BED Coverage] Update already in progress, skipping")
            return

        state["update_in_progress"] = True
        try:
            # Run heavy work in background thread
            thread = threading.Thread(target=_run_update, daemon=True)
            thread.start()
        except Exception as e:
            logger.exception(f"[BED Coverage] Failed to start background update: {e}")
            state["update_in_progress"] = False

    # Build UI — design.md §9: insight shell, cards, explicit .body--dark CSS
    with ui.element("div").classes("w-full min-w-0").props("id=analysis-detail-bed-coverage"):
        with ui.element("div").classes("classification-insight-shell w-full min-w-0"):
            ui.label("BED coverage").classes(
                "classification-insight-heading text-headline-small"
            )
            with ui.element("div").classes("classification-insight-card w-full min-w-0"):
                with ui.column().classes("w-full min-w-0 gap-2 p-2 md:p-3"):
                    with ui.row().classes("items-center gap-2 min-w-0"):
                        ui.icon("layers").classes("classification-insight-icon")
                        ui.label("Master BED genome coverage").classes(
                            "classification-insight-model flex-1 min-w-0"
                        )
                    state["bed_summary"] = ui.label(
                        "Awaiting visualization data"
                    ).classes("classification-insight-result w-full")
                    ui.label(
                        "Genome coverage proportion for each BED file type over time, "
                        "as new regions are identified."
                    ).classes("classification-insight-meta w-full")
                    ui.label(
                        "Data is written when master BED files are generated by the pipeline."
                    ).classes("classification-insight-foot")

            ui.label("Coverage over time").classes(
                "target-coverage-panel__meta-label mt-4 mb-1"
            )
            with ui.element("div").classes("w-full target-coverage-panel__plot-wrap"):
                state["chart"] = ui.echart(
                    {
                        "backgroundColor": "transparent",
                        "title": {
                            "text": "BED file genome coverage over time",
                            "left": "center",
                            "top": 10,
                            "textStyle": {"fontSize": 16},
                        },
                        "tooltip": {
                            "trigger": "axis",
                        },
                        "legend": {
                            "data": [],
                            "left": 10,
                            "top": "center",
                            "orient": "vertical",
                            "itemGap": 10,
                        },
                        "grid": {
                            "left": "15%",
                            "right": "5%",
                            "bottom": "10%",
                            "top": "20%",
                            "containLabel": True,
                        },
                        "xAxis": {
                            "type": "time",
                            "name": "Time",
                            "nameGap": 30,
                        },
                        "yAxis": {
                            "type": "value",
                            "name": "Genome coverage (%)",
                            "nameGap": 50,
                        },
                        "series": [],
                    }
                ).classes("w-full h-96")
                _apply_bed_cov_echart_chrome(state["chart"], _is_dark_mode())
                state["bed_cov_plot_theme_dark"] = _is_dark_mode()

            state["status_container"] = ui.column().classes("w-full mt-2 hidden")

    # Timer to check for results from background threads
    def check_result_queue() -> None:
        """Check for results from background thread and update UI."""
        try:
            while True:  # Process all available results
                result = state["result_queue"].get_nowait()
                _update_ui(result)
        except queue.Empty:
            # No result yet
            pass
        except Exception as e:
            logger.exception(f"[BED Coverage] Error processing result: {e}")

    result_timer = ui.timer(0.5, check_result_queue, active=True)

    def _sync_bed_cov_echarts_theme_if_needed() -> None:
        """Re-apply axis/tooltip/title colours when the user toggles light/dark mode."""
        try:
            dark = _is_dark_mode()
        except Exception:
            dark = False
        if state.get("bed_cov_plot_theme_dark") == dark:
            return
        ch = state.get("chart")
        if ch is not None:
            _apply_bed_cov_echart_chrome(ch, dark)
            try:
                ch.update()
            except Exception:
                pass
        state["bed_cov_plot_theme_dark"] = dark

    bed_cov_theme_timer = ui.timer(0.5, _sync_bed_cov_echarts_theme_if_needed, active=True)
    ui.timer(0.05, _sync_bed_cov_echarts_theme_if_needed, once=True)
    ui.timer(0.45, _sync_bed_cov_echarts_theme_if_needed, once=True)

    # Initial load - use a small delay to ensure chart is fully initialized
    def initial_load():
        try:
            _update_coverage_plot()
        except Exception as e:
            logger.exception(f"[BED Coverage] Initial load failed: {e}")

    ui.timer(0.1, initial_load, once=True)

    # Set up refresh timer (every 30 seconds)
    def refresh_coverage() -> None:
        """Refresh coverage data."""
        try:
            _update_coverage_plot()
        except Exception as e:
            logger.exception(f"[BED Coverage] Refresh failed: {e}")

    refresh_timer = ui.timer(30.0, refresh_coverage, active=True)
    try:
        ui.context.client.on_disconnect(
            lambda: (
                result_timer.deactivate(),
                refresh_timer.deactivate(),
                bed_cov_theme_timer.deactivate(),
            )
        )
    except Exception:
        pass
