from __future__ import annotations

from typing import Any, Dict, List, Optional
from pathlib import Path
import logging
import json
import os
from datetime import datetime
import threading
import queue

try:
    from nicegui import ui
except ImportError:  # pragma: no cover
    ui = None

logger = logging.getLogger("robin.gui.bed_coverage")


def _load_visualization_data(sample_dir: Path) -> Optional[Dict[str, Any]]:
    """
    Load pre-processed visualization data from JSON file.
    This data is generated by the analysis code to avoid doing heavy work in the GUI.
    
    Args:
        sample_dir: Sample directory path
        
    Returns:
        Dictionary with 'series' list for ECharts, or None if file not found or invalid
    """
    viz_file = sample_dir / "bed_coverage_viz.json"
    
    if not viz_file.exists():
        logger.debug(f"[BED Coverage] Visualization file not found: {viz_file}")
        return None
    
    try:
        with open(viz_file, 'r') as f:
            data = json.load(f)
            if isinstance(data, dict) and "series" in data:
                return data
            else:
                logger.warning(f"Visualization file has invalid format: {viz_file}")
                return None
    except (json.JSONDecodeError, IOError) as e:
        logger.warning(f"Could not load visualization data: {e}")
        return None


def add_bed_coverage_section(launcher: Any, sample_dir: Path) -> None:
    """
    Add BED coverage visualization section to the GUI.
    Shows genome coverage proportions for each BED file type over time.
    
    Args:
        launcher: GUI launcher instance
        sample_dir: Sample directory path
    """
    if ui is None:
        logger.warning("[BED Coverage] ui is None, returning early")
        return
    
    logger.info(f"[BED Coverage] add_bed_coverage_section() called with sample_dir: {sample_dir}")
    
    # Local state for this section
    state: Dict[str, Any] = {
        "mtime": None,
        "chart": None,
        "status_container": None,
        "update_in_progress": False,
        "result_queue": queue.Queue(),
        "chart_data": None,
    }
    
    
    def _update_ui(result: Optional[Dict[str, Any]]) -> None:
        """Update UI on main thread with results from background work."""
        try:
            # None means skip update (data unchanged)
            if result is None:
                return
            
            # Check if we have valid data
            if result.get("chart_data") is None:
                # Show message if visualization file not found or empty
                if state["status_container"]:
                    state["status_container"].clear()
                    state["status_container"].classes("w-full mt-2", replace="hidden")
                    with state["status_container"]:
                        ui.label("No BED coverage visualization data found").classes("text-gray-600")
                        ui.label("(Coverage data will appear after master BED files are generated)").classes("text-gray-500 text-xs")
                if state["chart"]:
                    state["chart"].classes("hidden", replace="w-full h-96")
                return
            
            # Update state
            state["mtime"] = result["mtime"]
            state["chart_data"] = result["chart_data"]
            chart_data = result["chart_data"]
            
            # Update chart if it exists and we have series to plot
            if state["chart"]:
                if chart_data["series"]:
                    logger.debug(f"[BED Coverage] Updating chart with {len(chart_data['series'])} series")
                    
                    # Extract legend data from series
                    legend_data = [s["name"] for s in chart_data["series"]]
                    
                    # Hide status container and ensure chart is visible BEFORE update
                    if state["status_container"]:
                        state["status_container"].classes("hidden")
                    # Ensure chart is visible - remove hidden class explicitly, then set classes
                    state["chart"].classes(remove="hidden")
                    state["chart"].classes("w-full h-96")
                    
                    # Update chart options
                    # Important: Directly modify the options dict in place
                    state["chart"].options["series"] = chart_data["series"]
                    state["chart"].options["legend"]["data"] = legend_data
                    # Update yAxis to format values as percentages
                    if "yAxis" in state["chart"].options:
                        state["chart"].options["yAxis"]["axisLabel"] = {"formatter": "{value}%"}
                    
                    # Force update
                    state["chart"].update()
                    logger.debug(f"[BED Coverage] Chart updated with {len(chart_data['series'])} series")
                else:
                    logger.warning("[BED Coverage] No series data to plot (all data points filtered out?)")
                    if state["status_container"]:
                        state["status_container"].classes("w-full mt-2", replace="hidden")
                        state["status_container"].clear()
                        with state["status_container"]:
                            ui.label("Coverage data exists but no valid data points to plot").classes("text-gray-600")
                    state["chart"].classes("hidden", replace="w-full h-96")
            else:
                # This shouldn't happen, but handle gracefully
                logger.warning("[BED Coverage] Chart element not initialized")
        except Exception as e:
            logger.exception(f"[BED Coverage] Failed to update UI: {e}")
            if state["status_container"]:
                state["status_container"].clear()
                state["status_container"].classes("w-full mt-2", replace="hidden")
                with state["status_container"]:
                    ui.label(f"Error loading coverage data: {str(e)}").classes("text-red-600")
            if state["chart"]:
                state["chart"].classes("hidden", replace="w-full h-96")
    
    def _update_coverage_plot() -> None:
        """Update the coverage plot. Data is pre-processed by analysis code."""
        def _do_heavy_work() -> Optional[Dict[str, Any]]:
            """Load pre-processed visualization data in background thread."""
            try:
                viz_file = sample_dir / "bed_coverage_viz.json"
                if not viz_file.exists():
                    return {"mtime": None, "chart_data": None}
                
                current_mtime = viz_file.stat().st_mtime
                
                # Skip if mtime hasn't changed and we already have data
                if current_mtime == state.get("mtime") and state.get("chart_data") is not None:
                    logger.debug("[BED Coverage] Data unchanged, skipping update")
                    return None  # Signal to skip UI update
                
                # Load pre-processed visualization data
                chart_data = _load_visualization_data(sample_dir)
                
                if chart_data and chart_data.get("series"):
                    logger.debug(f"[BED Coverage] Loaded visualization data with {len(chart_data['series'])} series")
                    return {
                        "mtime": current_mtime,
                        "chart_data": chart_data,
                    }
                else:
                    # File exists but no valid data
                    return {"mtime": current_mtime, "chart_data": None}
            except Exception as e:
                logger.exception(f"[BED Coverage] Error in background work: {e}")
            return None
        
        # Run heavy work in background thread, then put result in queue
        def _run_update():
            try:
                result = _do_heavy_work()
                # Put result in queue for main thread to pick up
                state["result_queue"].put(result)
            except Exception as e:
                logger.exception(f"[BED Coverage] Error in background thread: {e}")
                state["result_queue"].put(None)
            finally:
                state["update_in_progress"] = False
        
        # Check if update is already in progress
        if state.get("update_in_progress", False):
            logger.debug("[BED Coverage] Update already in progress, skipping")
            return
        
        state["update_in_progress"] = True
        try:
            # Run heavy work in background thread
            thread = threading.Thread(target=_run_update, daemon=True)
            thread.start()
        except Exception as e:
            logger.exception(f"[BED Coverage] Failed to start background update: {e}")
            state["update_in_progress"] = False
    
    # Build UI
    with ui.card().classes("w-full"):
        ui.label("📊 BED Coverage").classes("text-lg font-semibold mb-2")
        ui.label(
            "Genome coverage proportions for each BED file type over time. "
            "Shows how the proportion of the genome being targeted changes as new regions are identified."
        ).classes("text-sm text-gray-600 mb-2")
        
        # Create ECharts plot (similar to coverage.py)
        state["chart"] = ui.echart(
            {
                "backgroundColor": "transparent",
                "title": {
                    "text": "BED File Genome Coverage Over Time",
                    "left": "center",
                    "top": 10,
                    "textStyle": {"fontSize": 16, "color": "#000"},
                },
                "tooltip": {
                    "trigger": "axis",
                },
                "legend": {
                    "data": [],
                    "left": 10,
                    "top": "center",
                    "orient": "vertical",
                    "itemGap": 10,
                },
                "grid": {
                    "left": "15%",
                    "right": "5%",
                    "bottom": "10%",
                    "top": "20%",
                    "containLabel": True,
                },
                "xAxis": {
                    "type": "time",
                    "name": "Time",
                    "nameGap": 30,
                },
                "yAxis": {
                    "type": "value",
                    "name": "Genome Coverage (%)",
                    "nameGap": 50,
                },
                "series": [],
            }
        ).classes("w-full h-96")
        
        state["status_container"] = ui.column().classes("w-full mt-2 hidden")
    
    # Timer to check for results from background threads
    def check_result_queue() -> None:
        """Check for results from background thread and update UI."""
        try:
            while True:  # Process all available results
                result = state["result_queue"].get_nowait()
                _update_ui(result)
        except queue.Empty:
            # No result yet
            pass
        except Exception as e:
            logger.exception(f"[BED Coverage] Error processing result: {e}")
    
    result_timer = ui.timer(0.5, check_result_queue, active=True)
    
    # Initial load - use a small delay to ensure chart is fully initialized
    def initial_load():
        try:
            _update_coverage_plot()
        except Exception as e:
            logger.exception(f"[BED Coverage] Initial load failed: {e}")
    
    ui.timer(0.1, initial_load, once=True)
    
    # Set up refresh timer (every 30 seconds)
    def refresh_coverage() -> None:
        """Refresh coverage data."""
        try:
            _update_coverage_plot()
        except Exception as e:
            logger.exception(f"[BED Coverage] Refresh failed: {e}")
    
    refresh_timer = ui.timer(30.0, refresh_coverage, active=True)
    try:
        ui.context.client.on_disconnect(lambda: result_timer.deactivate())
        ui.context.client.on_disconnect(lambda: refresh_timer.deactivate())
    except Exception:
        pass
