#!/usr/bin/env python3
"""
Sturgeon analysis module for robin.

This module provides automated Sturgeon analysis following the exact architecture
specified in the Sturgeon Analysis Model. It integrates with robin's workflow
system and processes parquet files generated by the BED conversion step.

Features:
- Automated Sturgeon analysis using parquet files from BED conversion
- Integration with robin.subpages.Sturgeon_object
- Sample-specific output directories
- Comprehensive metadata extraction and logging
- Error handling and result tracking
"""

import os
import time
import logging
from dataclasses import dataclass, field
from typing import Dict, Any, Optional, List
from robin.logging_config import get_job_logger
from robin.analysis.utilities.merge_bedmethyl import (
    load_modkit_data,
    modkit_pileup_file_to_bed,
)
import tempfile
import gc
import pandas as pd
import numpy as np

# from robin.subpages.Sturgeon_object import predict_sample_from_dataframe

import sturgeon

# Sturgeon-related imports (must be installed)
from sturgeon.prediction import bed_to_numpy

import sys

import zipfile
import json
import onnxruntime
from sturgeon.utils import load_bed_file, softmax
from sturgeon.constants import NOMEASURE_VALUE

from robin import models

logger = logging.getLogger(__name__)


@dataclass
class SturgeonMetadata:
    """Container for Sturgeon analysis metadata and results"""

    sample_id: str
    parquet_path: str
    work_dir: str
    analysis_timestamp: float
    output_dir: Optional[str] = None
    processing_steps: List[str] = field(default_factory=list)
    error_message: Optional[str] = None
    results: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self):
        if self.processing_steps is None:
            self.processing_steps = []
        if self.results is None:
            self.results = {}


class SturgeonAnalysis:
    """Sturgeon analysis worker"""

    def __init__(self, work_dir=None):
        self.work_dir = work_dir or os.getcwd()

        # Use logger for initialization
        logger = logging.getLogger("robin.sturgeon")
        logger.info("Sturgeon Analysis initialized")
        logger.debug(f"Work directory: {self.work_dir}")

    def process_parquet_file(
        self, parquet_path: str, sample_id: str, work_dir: str
    ) -> SturgeonMetadata:
        """Process a parquet file for Sturgeon analysis"""
        logger = logging.getLogger("robin.sturgeon")

        logger.info(f"Processing parquet file: {parquet_path} for Sturgeon analysis")
        start_time = time.time()

        sturgeon_result = SturgeonMetadata(
            sample_id=sample_id,
            parquet_path=parquet_path,
            work_dir=work_dir,
            analysis_timestamp=start_time,
        )

        logger.info(f"Starting Sturgeon analysis for sample: {sample_id}")
        logger.debug(f"Parquet file: {os.path.basename(parquet_path)}")
        logger.debug(f"Work directory: {work_dir}")

        try:
            # Step 1: Check if parquet file exists and is readable
            if not os.path.exists(parquet_path):
                raise FileNotFoundError(f"Parquet file not found: {parquet_path}")

            sturgeon_result.processing_steps.append("file_validation")

            # Step 2: Create sample-specific output directory
            output_dir = os.path.join(work_dir, sample_id)
            os.makedirs(output_dir, exist_ok=True)
            sturgeon_result.output_dir = output_dir
            logger.info(f"Created output directory: {output_dir}")

            sturgeon_result.processing_steps.append("directory_created")

            # Step 3: Run Sturgeon analysis
            logger.info("Running Sturgeon analysis...")

            # Get reference genome and probes file
            reference_genome = "hg38"
            probes_file = self._get_probes_file(reference_genome)

            # Get current timestamp in milliseconds
            current_time = time.time() * 1000

            # Run Sturgeon analysis
            self._run_sturgeon_analysis(
                parquet_path, output_dir, probes_file, current_time
            )

            sturgeon_result.processing_steps.append("sturgeon_analysis_complete")

            logger.info(f"Sturgeon analysis complete for {sample_id}")
            logger.info(f"   Output directory: {output_dir}")
            logger.info(f"   Reference genome: {reference_genome}")
            logger.info(f"   Probes file: {os.path.basename(probes_file)}")

            return sturgeon_result

        except Exception as e:
            logger.error(f"Error in Sturgeon analysis for {sample_id}: {e}")
            sturgeon_result.error_message = str(e)
            sturgeon_result.processing_steps.append("analysis_failed")
            return sturgeon_result

    def _get_probes_file(self, reference_genome: str) -> str:
        """Get the probes file path for the given reference genome"""
        import os

        probes_file = os.path.join(
            os.path.dirname(sturgeon.__file__),
            "include/static",
            f"probes_{reference_genome}.bed",
        )
        return probes_file

    def _run_sturgeon_analysis(
        self, parquet_path: str, output_dir: str, probes_file: str, current_time: float
    ) -> None:
        """Run the actual Sturgeon analysis"""
        logger = logging.getLogger("robin.sturgeon")

        try:
            # Run the analysis directly using the top-level import
            # Create the output file path for sturgeon results
            # sturgeon_output_file = os.path.join(output_dir, "sturgeon.csv")
            sturgeon_bam_background_work(
                parquet_path, output_dir, str(probes_file), current_time
            )
            logger.debug("Sturgeon analysis completed successfully")

        except Exception as e:
            logger.error(f"Sturgeon analysis failed: {e}")
            raise


def process_multiple_files(parquet_paths, metadata_list, work_dir, logger):
    """
    Process multiple parquet files for sturgeon analysis.
    
    This function processes multiple parquet files for the same sample.
    Each file is processed individually and results are accumulated in
    the same sturgeon_scores.csv file.

    Args:
        parquet_paths: List of paths to parquet files
        metadata_list: List of metadata dictionaries (one per parquet file)
        work_dir: Working directory
        logger: Logger instance

    Returns:
        Dictionary with aggregated sturgeon analysis results
    """
    if not parquet_paths or not metadata_list:
        raise ValueError("parquet_paths and metadata_list must not be empty")
    
    if len(parquet_paths) != len(metadata_list):
        raise ValueError("parquet_paths and metadata_list must have the same length")
    
    # Get sample ID from first metadata (assuming all parquet files are from same sample)
    sample_id = metadata_list[0].get("sample_id", "unknown")
    
    logger.info(f"🐟 Starting multi-file sturgeon analysis for sample: {sample_id}")
    logger.info(f"Processing {len(parquet_paths)} parquet files for sample {sample_id}")
    
    # Log essential metadata only
    for i, (parquet_path, metadata) in enumerate(zip(parquet_paths, metadata_list)):
        logger.debug(f"Parquet file {i+1}: {os.path.basename(parquet_path)}")

    analysis_result = {
        "sample_id": sample_id,
        "parquet_paths": parquet_paths,
        "analysis_timestamp": time.time(),
        "processing_steps": [],
        "error_message": None,
        "files_processed": 0,
        "total_files": len(parquet_paths),
        "output_dir": None,
        "sturgeon_scores_path": None,
    }

    try:
        # Create sample-specific output directory
        output_dir = os.path.join(work_dir, sample_id)
        os.makedirs(output_dir, exist_ok=True)
        analysis_result["output_dir"] = output_dir
        analysis_result["sturgeon_scores_path"] = os.path.join(output_dir, "sturgeon_scores.csv")
        
        logger.info(f"Created output directory: {output_dir}")
        analysis_result["processing_steps"].append("directory_created")

        # Initialize sturgeon analysis
        sturgeon_analyzer = SturgeonAnalysis(work_dir=work_dir)
        
        # Get reference genome and probes file (shared across all files)
        reference_genome = "hg38"
        probes_file = sturgeon_analyzer._get_probes_file(reference_genome)
        logger.info(f"Using reference genome: {reference_genome}")
        logger.info(f"Using probes file: {os.path.basename(probes_file)}")

        # Process each parquet file individually
        logger.info("Processing parquet files individually")
        processed_files = 0
        
        for i, (parquet_path, metadata) in enumerate(zip(parquet_paths, metadata_list)):
            logger.info(f"Processing parquet file {i+1}/{len(parquet_paths)}: {os.path.basename(parquet_path)}")
            
            try:
                # Check if parquet file exists
                if not os.path.exists(parquet_path):
                    logger.warning(f"Parquet file not found: {parquet_path}")
                    continue
                
                # Get current timestamp in milliseconds
                current_time = time.time() * 1000
                
                # Run sturgeon analysis for this file
                sturgeon_analyzer._run_sturgeon_analysis(
                    parquet_path, output_dir, probes_file, current_time
                )
                
                processed_files += 1
                logger.debug(f"Successfully processed file {i+1}: {os.path.basename(parquet_path)}")
                
            except Exception as e:
                logger.warning(f"Error processing {os.path.basename(parquet_path)}: {e}")
                continue

        if processed_files == 0:
            analysis_result["error_message"] = "No files could be processed successfully"
            analysis_result["processing_steps"].append("no_files_processed")
            return analysis_result

        analysis_result["files_processed"] = processed_files
        analysis_result["processing_steps"].append("files_processed")

        # Check if sturgeon_scores.csv was created
        if os.path.exists(analysis_result["sturgeon_scores_path"]):
            analysis_result["processing_steps"].append("sturgeon_scores_created")
            logger.info(f"Sturgeon scores accumulated in: {analysis_result['sturgeon_scores_path']}")
        else:
            logger.warning("No sturgeon_scores.csv file was created")

        analysis_result["processing_steps"].append("analysis_complete")
        logger.info(f"Multi-file sturgeon analysis completed for {sample_id}")
        logger.info(f"Files successfully processed: {analysis_result['files_processed']}/{analysis_result['total_files']}")
        logger.info(f"Output directory: {analysis_result['output_dir']}")
        
        return analysis_result

    except Exception as e:
        logger.error(f"Error in multi-file sturgeon analysis for {sample_id}: {e}")
        analysis_result["error_message"] = str(e)
        analysis_result["processing_steps"].append("analysis_failed")
        return analysis_result


def sturgeon_handler(job, work_dir=None):
    """
    Handler function for Sturgeon analysis jobs.
    This function processes parquet files for Sturgeon analysis.

    Args:
        job: The workflow job containing file and metadata
        work_dir: Optional base directory for output (defaults to parquet file directory)
    """
    try:
        # Get job-specific logger
        logger = get_job_logger(str(job.job_id), job.job_type, job.context.filepath)
        
        # Check if this is a batched job
        batched_job = job.context.metadata.get("_batched_job")
        if batched_job:
            batch_size = batched_job.get_file_count()
            sample_id = batched_job.get_sample_id()
            batch_id = batched_job.batch_id
            logger.info(f"Processing sturgeon analysis batch: {batch_size} files for sample '{sample_id}' (batch_id: {batch_id})")
            
            # Get all filepaths in the batch
            filepaths = batched_job.get_filepaths()
            
            # Log individual files in the batch
            for i, filepath in enumerate(filepaths):
                logger.info(f"  Batch file {i+1}/{batch_size}: {os.path.basename(filepath)}")
            
            # Prepare metadata list and extract parquet paths from bed conversion results
            metadata_list = []
            parquet_paths = []
            
            for i, bam_path in enumerate(filepaths):
                # Get metadata from preprocessing for this specific file
                file_metadata = batched_job.contexts[i].metadata.get("bam_metadata", {})
                
                # Get sample ID from preprocessing results for this specific file
                file_context = batched_job.contexts[i]
                file_sample_id = file_context.get_sample_id()
                
                # Use the sample ID from the file's context (which should have preprocessing results)
                if file_sample_id != "unknown":
                    file_metadata["sample_id"] = file_sample_id
                else:
                    file_metadata["sample_id"] = sample_id
                
                # Get parquet path from bed conversion results for this file
                bed_conversion_result = batched_job.contexts[i].results.get("bed_conversion", {})
                parquet_path = bed_conversion_result.get("parquet_path")
                
                if parquet_path:
                    parquet_paths.append(parquet_path)
                    metadata_list.append(file_metadata)
                    logger.debug(f"Found parquet path for file {i+1}: {os.path.basename(parquet_path)}")
                else:
                    logger.warning(f"No parquet path found for file {i+1}: {os.path.basename(bam_path)}")
            
            if not parquet_paths:
                error_msg = "No parquet paths found from bed conversion results in batch"
                logger.error(error_msg)
                job.context.add_error("sturgeon_analysis", error_msg)
                return
            
            # Determine work directory for the batch
            if work_dir is None:
                # Default to first parquet file directory
                batch_work_dir = os.path.dirname(parquet_paths[0])
            else:
                # Use specified work directory, create if it doesn't exist
                os.makedirs(work_dir, exist_ok=True)
                batch_work_dir = work_dir
                logger.debug(f"Using specified work directory: {batch_work_dir}")
            
            # Process all parquet files in the batch using the new aggregated function
            logger.info(f"Processing {len(parquet_paths)} parquet files as aggregated batch for sample '{sample_id}'")
            batch_result = process_multiple_files(
                parquet_paths=parquet_paths,
                metadata_list=metadata_list,
                work_dir=batch_work_dir,
                logger=logger
            )
            
            # Store batch results in job context (maintain compatibility with existing structure)
            job.context.add_metadata("sturgeon_analysis", {
                "batch_result": batch_result,  # Single aggregated result
                "batch_size": batch_size,
                "sample_id": sample_id,
                "batch_id": batch_id,
                "files_processed": batch_result.get("files_processed", len(parquet_paths)),
                "total_files": batch_result.get("total_files", len(parquet_paths))
            })
            
            logger.info(f"Completed sturgeon analysis batch processing: {batch_size} files for sample '{sample_id}'")
            logger.info(f"Files successfully processed: {batch_result.get('files_processed', len(parquet_paths))}/{batch_result.get('total_files', len(parquet_paths))}")
            
            if batch_result.get("error_message"):
                logger.error(f"Batch processing completed with errors: {batch_result['error_message']}")
                job.context.add_error("sturgeon_analysis", batch_result["error_message"])
            else:
                logger.info("Batch processing completed successfully with aggregated sturgeon analysis")
                job.context.add_result(
                    "sturgeon_analysis",
                    {
                        "status": "success",
                        "sample_id": sample_id,
                        "analysis_time": batch_result.get("analysis_timestamp", 0),
                        "output_dir": batch_result.get("output_dir", ""),
                        "processing_steps": batch_result.get("processing_steps", []),
                        "sturgeon_scores_path": batch_result.get("sturgeon_scores_path", ""),
                        "files_processed": batch_result.get("files_processed", len(parquet_paths)),
                        "total_files": batch_result.get("total_files", len(parquet_paths)),
                    },
                )
            
            return
            
        else:
            # Single file processing (backward compatibility)
            logger.info(
                f"Starting Sturgeon analysis for: {os.path.basename(job.context.filepath)}"
            )

            # Get metadata from previous steps
            bed_conversion_result = job.context.results.get("bed_conversion", {})
            bam_metadata = job.context.metadata.get("bam_metadata", {})

            # Extract parquet path from bed conversion results
            parquet_path = bed_conversion_result.get("parquet_path")
            if not parquet_path:
                raise ValueError("No parquet path found from bed conversion step")

            # Get sample ID
            sample_id = bam_metadata.get("sample_id", "unknown")

            # Determine work directory
            if work_dir is None:
                # Default to parquet file directory
                work_dir = os.path.dirname(parquet_path)
            else:
                # Use specified work directory, create if it doesn't exist
                os.makedirs(work_dir, exist_ok=True)
                logger.debug(f"Using specified work directory: {work_dir}")

            # Create Sturgeon analysis instance
            sturgeon_analyzer = SturgeonAnalysis(work_dir=work_dir)

            # Process the parquet file
            sturgeon_result = sturgeon_analyzer.process_parquet_file(
                parquet_path, sample_id, work_dir
            )

            # Store results in job context
            job.context.add_metadata("sturgeon_analysis", sturgeon_result.results)
            job.context.add_metadata(
                "sturgeon_processing_steps", sturgeon_result.processing_steps
            )

            if sturgeon_result.error_message:
                job.context.add_error("sturgeon_analysis", sturgeon_result.error_message)
                logger.error(f"Sturgeon analysis failed: {sturgeon_result.error_message}")
            else:
                job.context.add_result(
                    "sturgeon_analysis",
                    {
                        "status": "success",
                        "sample_id": sturgeon_result.sample_id,
                        "analysis_time": sturgeon_result.analysis_timestamp,
                        "output_dir": sturgeon_result.output_dir,
                        "processing_steps": sturgeon_result.processing_steps,
                    },
                )
                logger.info(
                    f"Sturgeon analysis complete for {os.path.basename(job.context.filepath)}"
                )
                logger.info(f"Sample ID: {sturgeon_result.sample_id}")
                logger.info(f"Output directory: {sturgeon_result.output_dir}")
                logger.debug(
                    f"Processing steps: {', '.join(sturgeon_result.processing_steps)}"
                )

    except Exception as e:
        job.context.add_error("sturgeon_analysis", str(e))
        logger.error(f"Error in Sturgeon analysis for {job.context.filepath}: {e}")


def sturgeon_bam_background_work(parquet_path, output_path, probes_file, currenttime):
    # Initialize variables to None for cleanup
    merged_modkit_df = None
    result_df = None
    diagnosis = None
    mydf_to_save = None
    sturgeon_df_store = None

    try:
        # if self.check_file_time(parquet_path):
        # merged_modkit_df = await run.cpu_bound(
        #    load_modkit_data, parquet_path
        # )

        merged_modkit_df = load_modkit_data(parquet_path)
        with tempfile.NamedTemporaryFile(dir=output_path, delete=True) as temp_pileup:
            result_df = modkit_pileup_file_to_bed(
                merged_modkit_df,
                temp_pileup.name,
                probes_file,
            )
            diagnosis = predict_sample_from_dataframe(result_df)
            mydf_to_save = diagnosis
            mydf_to_save["timestamp"] = currenttime

            # if self.check_file_time(os.path.join(self.output, sampleID, "sturgeon_scores.csv")):
            if os.path.exists(os.path.join(output_path, "sturgeon_scores.csv")):
                sturgeon_df_store = pd.read_csv(
                    os.path.join(os.path.join(output_path, "sturgeon_scores.csv")),
                    index_col=0,
                )
            else:
                sturgeon_df_store = pd.DataFrame()

            # Exclude empty or all-NA entries before concatenation
            if not mydf_to_save.dropna(how="all").empty:
                # Create a copy for concatenation to avoid modifying original
                mydf_indexed = mydf_to_save.set_index("timestamp")
                sturgeon_df_store = pd.concat(
                    [
                        sturgeon_df_store,
                        mydf_indexed,
                    ]
                )
                sturgeon_df_store.to_csv(
                    os.path.join(
                        output_path,
                        "sturgeon_scores.csv",
                    )
                )
                # Clean up the indexed copy
                del mydf_indexed

    except Exception as e:
        print(f"Error in process_bam (sturgeon): {e}")
        logger.error(f"Error in process_bam (sturgeon): {e}")
    finally:
        # Comprehensive cleanup of all large DataFrames and variables
        if merged_modkit_df is not None:
            del merged_modkit_df
        if result_df is not None:
            del result_df
        if diagnosis is not None:
            del diagnosis
        if mydf_to_save is not None:
            del mydf_to_save
        if sturgeon_df_store is not None:
            del sturgeon_df_store

        # Force garbage collection
        gc.collect()


def predict_sample_from_dataframe(
    bed_df: pd.DataFrame,
    # model_file: str,
    # output_dir: str,
    sample_name: str = "sample",
    plot_results: bool = False,
):
    """
    Runs `predict_sample` using a DataFrame instead of a BED file.

    Parameters:
        bed_df (pd.DataFrame): The BED file data as a DataFrame.
        model_file (str): Path to the trained model file.
        #output_dir (str): Directory to save results.
        #sample_name (str): Name identifier for output files.
        plot_results (bool): Whether to generate a plot.

    Returns:
        pd.DataFrame: The prediction results.
    """
    import subprocess
    import json
    import tempfile

    # Alternative multiprocessing approach (uncomment to use):
    """
    import multiprocessing as mp
    import pickle
    
    def run_prediction_worker(model_file, bed_file, result_queue):
        try:
            prediction_df = run_sturgeon_mem_free(model_file, bed_file)
            result_queue.put(('success', prediction_df))
        except Exception as e:
            result_queue.put(('error', str(e)))
    
    # Save DataFrame as temporary file
    with tempfile.NamedTemporaryFile(delete=True, suffix=".bed") as tmp_bed:
        temp_bed_file = tmp_bed.name
        bed_df.to_csv(temp_bed_file, sep="\t", index=False, header=True)
        
        # Create queue for results
        result_queue = mp.Queue()
        
        # Start prediction process
        process = mp.Process(
            target=run_prediction_worker,
            args=(modelfile, temp_bed_file, result_queue)
        )
        process.start()
        process.join(timeout=300)  # 5 minute timeout
        
        if process.is_alive():
            process.terminate()
            process.join()
            raise RuntimeError("Prediction timed out after 5 minutes")
        
        # Get results
        status, result = result_queue.get()
        if status == 'error':
            raise RuntimeError(f"Prediction failed: {result}")
        
        return result
    """

    # Ensure output directory exists
    # os.makedirs(output_dir, exist_ok=True)
    modelfile = os.path.join(
        os.path.dirname(os.path.abspath(models.__file__)), "general.zip"
    )

    # Save DataFrame as a temporary BED file
    with tempfile.NamedTemporaryFile(delete=False, suffix=".bed") as tmp_bed:
        temp_bed_file = tmp_bed.name
        bed_df.to_csv(temp_bed_file, sep="\t", index=False, header=True)

    try:
        # Run prediction directly (no subprocess needed in Ray workflow)
        prediction_df = run_sturgeon_mem_free(modelfile, temp_bed_file)
        return prediction_df
    except Exception as e:
        raise RuntimeError(f"Prediction failed: {str(e)}")
    finally:
        # Clean up temporary file
        try:
            os.unlink(temp_bed_file)
        except Exception:
            pass


def model_forward(
    x: np.ndarray, inference_session: onnxruntime.InferenceSession
) -> np.ndarray:

    # compute ONNX Runtime output prediction
    ort_value = None
    try:
        ort_value = onnxruntime.OrtValue.ortvalue_from_numpy(x)
        ort_inputs = {inference_session.get_inputs()[0].name: ort_value}
        ort_outs = inference_session.run(["predictions"], ort_inputs)[0]
        return ort_outs[0]
    finally:
        if ort_value is not None:
            del ort_value


def run_sturgeon_mem_free(model_file, bed_file):
    # Initialize variables to None for cleanup
    zipf = None
    probes_df = None
    decoding_dict = None
    temperatures = None
    so = None
    inference_session = None
    x = None
    scores = None
    calibrated_scores = None
    calibrated_df = None
    avg_scores = None
    final_scores = None
    prediction_df = None
    arr = None
    best_m = None

    try:
        zipf = zipfile.ZipFile(model_file, "r")

        logging.debug("Loading probes information")
        probes_df = pd.read_csv(
            zipf.open("probes.csv"),
            header=0,
            index_col=None,
        )

        logging.debug("Loading the decoding dict")
        decoding_dict = json.load(zipf.open("decoding.json"))

        logging.debug("Loading calibration matrix")
        try:
            temperatures = np.load(zipf.open("calibration.npy"))
            temperatures = temperatures.flatten()
        except KeyError:
            logging.debug("No calibration matrix in zip file")
            temperatures = None

        logging.info("Starting inference session")
        so = onnxruntime.SessionOptions()
        so.inter_op_num_threads = 1

        inference_session = onnxruntime.InferenceSession(
            zipf.read("model.onnx"),
            providers=["CPUExecutionProvider"],
            sess_options=so,
        )
        requires_calibration = False
        if temperatures is not None:
            requires_calibration = True

        logging.info("Loading bed file: {}".format(bed_file))
        x = bed_to_numpy(bed_df=load_bed_file(bed_file), probes_df=probes_df)
        scores = model_forward(x, inference_session)

        calibrated_scores = np.empty_like(scores)
        for i in range(scores.shape[0]):
            if requires_calibration:
                calibrated_scores[i, :] = np.exp(
                    softmax(scores[i, :] / temperatures[i])
                )
            else:
                calibrated_scores[i, :] = np.exp(softmax(scores[i, :]))

        calibrated_df = dict()
        for k, v in decoding_dict.items():
            calibrated_df[v] = calibrated_scores[:, int(k)]
        calibrated_df = pd.DataFrame(calibrated_df)

        n = np.sum(x != NOMEASURE_VALUE)

        avg_scores = {
            "number_probes": [n],
        }

        final_scores = list()
        arr = np.array(calibrated_df[calibrated_df.columns])
        best_m = np.where(arr == np.max(arr))[0]
        if len(best_m) > 0:
            best_m = best_m[0]
        for colname in calibrated_df.columns:
            score = np.array(calibrated_df[colname])[best_m].item()
            avg_scores[colname] = [score]
            final_scores.append(score)
        final_scores = np.array(final_scores)

        prediction_df = pd.DataFrame(avg_scores, index=[0])

    finally:
        # Proper ONNX cleanup
        if inference_session is not None:
            try:
                inference_session.set_providers([])
                del inference_session
            except Exception as e:
                logger.error(f"Failed to delete inference session: {e}")
                pass

        # Comprehensive cleanup of all variables
        if so is not None:
            del so
        if probes_df is not None:
            del probes_df
        if decoding_dict is not None:
            del decoding_dict
        if temperatures is not None:
            del temperatures
        if x is not None:
            del x
        if scores is not None:
            del scores
        if calibrated_scores is not None:
            del calibrated_scores
        if calibrated_df is not None:
            del calibrated_df
        if arr is not None:
            del arr
        if best_m is not None:
            del best_m
        if final_scores is not None:
            del final_scores
        if avg_scores is not None:
            del avg_scores
        if zipf is not None:
            zipf.close()

        # Force ONNX runtime cleanup
        try:
            import onnxruntime as ort

            # Clear any cached memory by getting device info
            ort.get_device()
        except Exception as e:
            logger.error(f"Failed to clear cached memory: {e}")
            pass

        # Force garbage collection
        gc.collect()

    return prediction_df


if __name__ in {"__main__", "__mp_main__"}:
    # This is the main module - no subprocess handling needed
    print("Sturgeon analysis module loaded.")
